### ISSUE TITLE
Erro while trying to upload source map files

### ISSUE THREAD

**Issue by danielmariz-hotmart** [ikenfin/vite-plugin-sentry#278]
I'm getting this error on build 
```
error during build:
RollupError: Error while uploading sourcemaps to Sentry: spawn /runner/_work/app-account/app-account/node_modules/@sentry/cli/sentry-cli ENOENT
    at error (file:///runner/_work/app-folder/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at error (file:///runner/_work/app-folder/node_modules/rollup/dist/es/shared/node-entry.js:241[50]
    at Object.<anonymous> (file:///runner/_work/app-folder/node_modules/vite-plugin-sentry/dist/index.mjs:243:29)
    at Generator.throw (<anonymous>)
    at rejected (file:///runner/_work/app-folder/node_modules/vite-plugin-sentry/dist/index.mjs:23:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Process completed with exit code 1.
```
Do you have any idea what can cause it? I'm following the basic config from the docs
Cheers

**Comment by ikenfin** [comment]
Hi! 
Seems like there are some problem with sentry/cli. 

ENOENT means that file was not found - can you check that `/runner/_work/app-account/app-account/node_modules/@sentry/cli/sentry-cli` is exists?

If so - also try to run with using Sentry debug env variable, like so `SENTRY_LOG_LEVEL=info npm run build # replace with your npm script`

**Comment by danielmariz-hotmart** [comment]
Thanks for the response.

Locally the sentry-cli exits
<img width="353" alt="Screenshot 2023-04-27 at 09 07 42" src="https://user-images.githubusercontent.com/118078941/234873060-79d4d2fa-a78b-4454-9900-d0a9c2fe98b0.png">

but on github actions pipeline it only exists on  bin folder
```
Run ls -lah node_modules/@sentry/cli
total 20K
drwxr-sr-x  5 runner docker  115 Apr 27 13:09 .
drwxr-sr-x 13 runner docker  170 Apr 27 13:09 ..
-rw-r--r--  1 runner docker 1.5K Apr 27 13:09 LICENSE
-rw-r--r--  1 runner docker 5.2K Apr 27 13:09 README.md
drwxr-sr-x  2 runner docker   24 Apr 27 13:09 bin
-rw-r--r--  1 runner docker  8[14](https://github.com/*ORG*/app-demo/actions/runs/4820169577/jobs/8584292206#step:9:15) Apr 27 13:09 checksums.txt
drwxr-sr-x  3 runner docker   90 Apr 27 13:09 js
-rw-r--r--  1 runner docker 1.6K Apr 27 13:09 package.json
drwxr-sr-x  2 runner docker  113 Apr 27 13:09 scripts
total 4.0K
drwxr-sr-x 2 runner docker  24 Apr 27 13:09 .
drwxr-sr-x 5 runner docker 1[15](https://github.com/**ORG**/app-demo/actions/runs/4820169577/jobs/8584292206#step:9:16) Apr [27](https://github.com/**Org**/app-account/actions/runs/4820169577/jobs/8584292206#step:9:28) 13:09 ..
-rwxr-xr-x 1 runner docker 487 Apr 27 13:09 sentry-cli
```

Also found this [related issue ](https://github.com/expo/sentry-expo/issues/117)

shouldn't this be pointing to the bin folder? 🤔
